### ISSUE TITLE
Small error in code 

### ISSUE THREAD

**Issue by aleejessop** [a-l-davis/Schweikert-et-al.-2020#2]
Hi there, 

I've been using your equations for a paper I'm working on and have been trying to replicate them in MatLab but I was struggling to replicate the results from your paper. So I downloaded this code and I'm sorry to say that I noticed that the way you average the integration times is incorrect and this was why I was getting different results. The integrations times need to be in brackets before they are divided by 2, otherwise it gives you an integration time that is larger than both the times that you are trying to average.

Thanks,

Annie Jessop

**Comment by a-l-davis** [comment]
Hi Annie, 

Thank you for alerting me to the issue, and sorry you had to waste time catching my errors! I will update the code for future users and redo the calculations to see if sighting distance is affected meaningfully. 

Best,
Alex
